IBM/nl2flow

- profiler/converters/converter_variables.py
- profiler/converters/info_2_flow_converter.py
- profiler/data_types/generator_data_type.py
- profiler/generators/batch_data_generator/batch_data_generator.py
- profiler/generators/dataset_generator/dataset_generator.py
- profiler/generators/info_generator/agent_info_generator.py
- pyproject.toml
- tests/conftest/conftest.py
- tests/profiler/data_types/test_generator_data_type.py
- tests/profiler/generators/batch_data_generator/test_batch_data_generator.py
With this change, planning data generation can start.
https://github.com/IBM/nl2flow/issues/9
> Generator wrapper

- profiler/data_types/generator_data_type.py
https://github.com/IBM/nl2flow/issues/15
> Change Enum type for name generator to store data at MongoDB

- profiler/generators/dataset_generator/dataset_generator.py
- profiler/generators/description_generator/descripter_generator_data.py
- profiler/generators/description_generator/description_generator.py
- profiler/generators/description_generator/description_generator_helper.py
- profiler/validators/agent_info_generator_test_utils.py
- tests/profiler/generators/description_generator/test_description_generator_helper.py
https://github.com/IBM/nl2flow/issues/21
https://github.com/IBM/nl2flow/issues/22
https://github.com/IBM/nl2flow/issues/23
> Revise Natural Language Problem + Domain Description

- pyproject.toml
- tests/profiler/common_helpers/test_time_helper.py
- tests/profiler/converters/test_info_2_flow_converter.py
- tests/profiler/data_types/test_generator_data_type.py
- tests/profiler/generators/batch_data_generator/test_batch_data_generator.py
- tests/profiler/generators/dataset_generator/test_dataset_generator.py
- tests/profiler/generators/description_generator/test_description_generator.py
- tests/profiler/generators/description_generator/test_description_generator_helper.py
- tests/profiler/generators/info_generator/test_agent_info_generator.py
- tests/profiler/generators/info_generator/test_agent_info_generator_helper.py
- tests/profiler/generators/info_generator/test_info_generator_coupling_helper.py
- tests/profiler/generators/quadruple_generator/test_quadruple_generator.py
- tests/profiler/validators/test_validator_executor.py
https://github.com/IBM/nl2flow/issues/28
All tests run as pytest.
> Remove unittest

- profiler/data_types/pddl_generator_datatypes.py
- profiler/generators/dataset_generator/dataset_generator.py
- profiler/generators/description_generator/description_generator_helper.py
- pyproject.toml
- tests/profiler/generators/batch_data_generator/test_batch_data_generator.py
- tests/profiler/generators/description_generator/test_description_generator_helper.py
- tests/profiler/generators/info_generator/test_info_generator_coupling_helper.py
https://github.com/IBM/nl2flow/issues/31
https://github.com/IBM/nl2flow/issues/37
To resolve some type errors, execute the following command. This dependency is added to pyproject.toml.
`python3 -m pip install types-PyYAML`
> Fix a bug in variable description and add prettified plans to generator outputs

- .pre-commit-config.yaml
- nl2flow/compile/basic_compilations/compile_goals.py
- nl2flow/compile/flow.py
- nl2flow/plan/utils.py
- profiler/generators/description_generator/descripter_generator_data.py
- profiler/validators/agent_info_generator_test_utils.py
https://github.com/IBM/nl2flow/issues/41
> Remove type description for mapping

- .gitignore
- profiler/converters/converter_variables.py
- profiler/converters/info_2_flow_converter.py
- profiler/data_types/agent_info_data_types.py
- profiler/data_types/generator_output_data_type.py
- profiler/generators/batch_data_generator/batch_data_generator.py
- profiler/generators/dataset_generator/dataset_generator.py
- profiler/generators/description_generator/description_generator.py
- profiler/generators/description_generator/description_generator_helper.py
- profiler/generators/info_generator/agent_info_generator_coupling_helper.py
- profiler/generators/info_generator/agent_info_generator_helper.py
- profiler/generators/info_generator/generator_variables.py
- profiler/validators/agent_info_generator_test_utils.py
- profiler/validators/validator_executer.py
- pyproject.toml
- tests/profiler/converters/test_info_2_flow_converter.py
- tests/profiler/generators/description_generator/test_description_generator_helper.py
- tests/profiler/generators/info_generator/test_agent_info_generator_helper.py
- tests/profiler/generators/info_generator/test_info_generator_coupling_helper.py
Remove TypedDict from NL2FLOW.
No functional change.
https://github.com/IBM/nl2flow/issues/39
> Remove TypedDict from NL2FLOW

- profiler/data_types/pddl_generator_datatypes.py
- profiler/generators/dataset_generator/dataset_generator.py
To record errors in data generation.
> Add planner response to generator output

- profiler/data_types/agent_info_data_types.py
- tests/profiler/generators/description_generator/test_description_generator_helper.py
This is to improve code maintainability.
https://github.com/IBM/nl2flow/issues/51
> Remove deprecated fields in AgentInfoSignatureItem

- nl2flow/plan/planners.py
- nl2flow/utility/file_utility.py
https://github.com/IBM/nl2flow/issues/62
> Atomic file writing

- nl2flow/compile/basic_compilations/compile_goals.py
- nl2flow/compile/basic_compilations/compile_history.py
- nl2flow/compile/basic_compilations/compile_operators.py
- nl2flow/compile/basic_compilations/compile_reference.py
- nl2flow/compile/compilations.py
- nl2flow/compile/flow.py
- nl2flow/compile/options.py
- tests/optimizations/test_no_instances.py
#18 Flag to toggle between parameterized and unparameterized compilations
> retry and multi instance flags

- pyproject.toml
- tests/goals/test_goals_basic.py
- tests/history/test_history_progression.py
- tests/retry/test_retry.py
> documentation

- profiler/converters/info_2_flow_converter.py
https://github.com/IBM/nl2flow/issues/64
> Basic profiler setting

- profiler/data_types/pddl_generator_datatypes.py
- profiler/generators/dataset_generator/dataset_generator.py
https://github.com/IBM/nl2flow/issues/74
> Add a seed to flow to PddlGeneratorOutput

- profiler/data_types/generator_output_data_type.py
- profiler/generators/dataset_generator/dataset_generator.py
- profiler/generators/description_generator/description_generator.py
- profiler/generators/description_generator/description_generator_helper.py
- profiler/generators/info_generator/agent_info_generator_helper.py
- profiler/validators/agent_info_generator_test_utils.py
https://github.com/IBM/nl2flow/issues/76
> Store goal as list in profiler

- profiler/generators/description_generator/descripter_generator_data.py
- profiler/generators/description_generator/description_generator.py
- profiler/generators/description_generator/description_generator_helper.py
- tests/profiler/generators/description_generator/test_description_generator_helper.py
https://github.com/IBM/nl2flow/issues/81
> Update planning prompt

- profiler/generators/description_generator/description_generator.py
- profiler/generators/description_generator/description_generator_helper.py
Describe each action in one line.
https://github.com/IBM/nl2flow/issues/81
> Describe each action in one line

- profiler/data_types/generator_data_type.py
- profiler/generators/info_generator/agent_info_generator_helper.py
- profiler/validators/agent_info_generator_test_utils.py
- tests/profiler/generators/dataset_generator/test_dataset_generator.py
https://github.com/IBM/nl2flow/issues/100
> Generate planning problems with one action

- profiler/data_types/generator_output_data_type.py
- profiler/generators/dataset_generator/dataset_generator.py
https://github.com/IBM/nl2flow/issues/102
> Generate generator sample hash with ONLY PDDL

- profiler/data_types/generator_data_type.py
- profiler/data_types/pddl_generator_datatypes.py
- profiler/generators/dataset_generator/dataset_generator.py
- profiler/generators/info_generator/agent_info_generator_helper.py
- profiler/validators/agent_info_generator_test_utils.py
- pyproject.toml
https://github.com/IBM/nl2flow/issues/104
> Include tags in PddlGeneratorOutput

- profiler/converters/info_2_flow_converter.py
- profiler/data_types/agent_info_data_types.py
- profiler/data_types/generator_data_type.py
- profiler/data_types/generator_output_data_type.py
- profiler/generators/batch_data_generator/batch_data_generator.py
- profiler/generators/dataset_generator/dataset_generator.py
- profiler/generators/description_generator/description_generator.py
- profiler/generators/description_generator/description_generator_helper.py
- tests/profiler/converters/test_info_2_flow_converter.py
- tests/profiler/data_types/test_agent_info_data_type.py
- tests/profiler/data_types/test_generator_data_type.py
- tests/profiler/generators/description_generator/test_description_generator_helper.py
https://github.com/IBM/nl2flow/issues/108
> Generator handles should_objects_known_in_memory field

- profiler/data_types/pddl_generator_datatypes.py
https://github.com/IBM/nl2flow/issues/110
> Update objects_in_memory flag logic for should_objects_known_in_memory

- nl2flow/compile/utils.py
> iss119 hotfix

- nl2flow/compile/basic_compilations/compile_operators.py
- nl2flow/compile/schemas.py
- nl2flow/plan/planner.py
- tests/basic/test_basic.py
- tests/slots/test_optional_parameters.py
> Compilation updates

- nl2flow/compile/basic_compilations/compile_history.py
- nl2flow/compile/basic_compilations/compile_references/compile_reference_basic.py
- nl2flow/compile/compilations.py
- nl2flow/compile/flow.py
- nl2flow/debug/debug.py
- nl2flow/debug/schemas.py
- nl2flow/plan/planners/kstar.py
+ [x] Memory fix for repetition 
+ [x] Changes for compression compilation
+ [x] Cost model for debugging
> Refraction Release

- pyproject.toml
@TathagataChakraborti Test this change to see if the version set at the Github UI is used for creating artifacts for the package.
Related Issue:
https://github.com/IBM/nl2flow/issues/155
> Update pyproject.yml to dynamically set version from Git

- pyproject.toml
Reorder command for setuptools_scm
> Reorder command for setuptools_scm
